/**
 * AUTO-GENERATED by scripts/generate-sdk-errors.ts — DO NOT EDIT.
 * Regenerate with: npm run generate:sdk-errors
 */

export interface CredenceErrorEnvelope {
  error: string
  code: string
  details?: unknown
}

export interface CredenceErrorOptions {
  cause?: unknown
  rawBody?: string
}

export interface SanitizedErrorCause {
  name?: string
  message?: string
  code?: string
  cause?: SanitizedErrorCause
}

const DEFAULT_MESSAGES = {
  'validation_failed': "Validation failed",
  'field_required': "A required field is missing",
  'invalid_format': "The request contains a field with an invalid format",
  'invalid_address': "The request contains an invalid address",
  'value_too_small': "The request contains a value below the allowed minimum",
  'value_too_large': "The request contains a value above the allowed maximum",
  'unexpected_field': "The request contains an unexpected field",
  'invalid_type': "The request contains a field with an invalid type",
  'unsafe_redirect_target': "The requested redirect target is not permitted",
  'invalid_stellar_address': "The request contains an invalid Stellar address",
  'batch_size_too_small': "The batch size is below the allowed minimum",
  'batch_size_exceeded': "The batch size exceeds the allowed maximum",
  'request_too_large': "The request body exceeds the maximum allowed size",
  'unauthorized': "Authentication is required",
  'forbidden': "The authenticated caller is not allowed to perform this action",
  'crawler_blocked': "Automated crawling of admin surfaces is forbidden.",
  'not_found': "The requested resource was not found",
  'conflict': "The request conflicts with the current resource state",
  'optimistic_lock_conflict': "The resource was modified by another request. Fetch the latest version and retry.",
  'idempotency_key_mismatch': "Idempotency key is already bound to a different actor or payload",
  'insufficient_credits': "Monthly credit budget exhausted",
  'ssrf_blocked': "The target URL resolves to a restricted or internal network address",
  'insufficient_funds': "The account has insufficient funds for this operation",
  'invalid_dispute_transition': "Invalid dispute state transition",
  'rate_limit_exceeded': "Rate limit exceeded",
  'internal_server_error': "An unexpected internal server error occurred",
  'service_unavailable': "Service temporarily unavailable",
  'missing_security_header': "A required security response header is missing",
  'invalid_input': "Invalid input",
  'sdk_request_timeout': "Request timed out",
  'sdk_network_error': "Network error",
  'sdk_invalid_json': "Invalid JSON response",
  'sdk_unmapped_http': "Unmapped HTTP error response",
} as const

/**
 * Strip stack traces from an Error cause chain before serialization or attachment.
 * Prevents server-side stack traces from leaking through nested causes.
 */
export function sanitizeCauseChain(cause: unknown): SanitizedErrorCause | undefined {
  if (cause == null) return undefined

  if (cause instanceof Error) {
    const sanitized: SanitizedErrorCause = {
      name: cause.name,
      message: cause.message,
    }

    const nodeCode = (cause as Error & { code?: unknown }).code
    if (typeof nodeCode === 'string') {
      sanitized.code = nodeCode
    }

    if (cause.cause != null) {
      sanitized.cause = sanitizeCauseChain(cause.cause)
    }

    return sanitized
  }

  if (typeof cause === 'object') {
    const record = cause as Record<string, unknown>
    const sanitized: SanitizedErrorCause = {}

    if (typeof record.name === 'string') sanitized.name = record.name
    if (typeof record.message === 'string') sanitized.message = record.message
    if (typeof record.code === 'string') sanitized.code = record.code
    if ('cause' in record) sanitized.cause = sanitizeCauseChain(record.cause)

    return Object.keys(sanitized).length > 0 ? sanitized : undefined
  }

  return { message: String(cause) }
}

export class CredenceError extends Error {
  public readonly code: string
  public readonly status: number
  public readonly details?: unknown
  public readonly rawBody?: string

  constructor(
    message: string,
    code: string,
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, {
      cause:
        options?.cause != null ? sanitizeCauseChain(options.cause) : undefined,
    })
    this.name = 'CredenceError'
    this.code = code
    this.status = status
    this.details = details
    this.rawBody = options?.rawBody
  }

  toJSON(): CredenceErrorEnvelope & { status: number; rawBody?: string } {
    return {
      error: this.message,
      code: this.code,
      status: this.status,
      ...(this.details !== undefined ? { details: this.details } : {}),
      ...(this.rawBody !== undefined ? { rawBody: this.rawBody } : {}),
    }
  }
}

/**
 * Common construct signature shared by every generated CredenceError subclass.
 * Subclasses pin their `code` internally, so the public constructor is
 * `(message, status, details?, options?)`. The registry is keyed by code and
 * always instantiated via this shape.
 */
export type CredenceErrorConstructor = new (
  message: string,
  status: number,
  details?: unknown,
  options?: CredenceErrorOptions,
) => CredenceError

export class ValidationFailedCredenceError extends CredenceError {
  static readonly errorCode = 'validation_failed' as const

  constructor(
    message: string = DEFAULT_MESSAGES['validation_failed'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'validation_failed', status, details, options)
    this.name = 'ValidationFailedCredenceError'
  }
}

export class FieldRequiredCredenceError extends CredenceError {
  static readonly errorCode = 'field_required' as const

  constructor(
    message: string = DEFAULT_MESSAGES['field_required'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'field_required', status, details, options)
    this.name = 'FieldRequiredCredenceError'
  }
}

export class InvalidFormatCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_format' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_format'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_format', status, details, options)
    this.name = 'InvalidFormatCredenceError'
  }
}

export class InvalidAddressCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_address' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_address'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_address', status, details, options)
    this.name = 'InvalidAddressCredenceError'
  }
}

export class ValueTooSmallCredenceError extends CredenceError {
  static readonly errorCode = 'value_too_small' as const

  constructor(
    message: string = DEFAULT_MESSAGES['value_too_small'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'value_too_small', status, details, options)
    this.name = 'ValueTooSmallCredenceError'
  }
}

export class ValueTooLargeCredenceError extends CredenceError {
  static readonly errorCode = 'value_too_large' as const

  constructor(
    message: string = DEFAULT_MESSAGES['value_too_large'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'value_too_large', status, details, options)
    this.name = 'ValueTooLargeCredenceError'
  }
}

export class UnexpectedFieldCredenceError extends CredenceError {
  static readonly errorCode = 'unexpected_field' as const

  constructor(
    message: string = DEFAULT_MESSAGES['unexpected_field'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'unexpected_field', status, details, options)
    this.name = 'UnexpectedFieldCredenceError'
  }
}

export class InvalidTypeCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_type' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_type'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_type', status, details, options)
    this.name = 'InvalidTypeCredenceError'
  }
}

export class UnsafeRedirectTargetCredenceError extends CredenceError {
  static readonly errorCode = 'unsafe_redirect_target' as const

  constructor(
    message: string = DEFAULT_MESSAGES['unsafe_redirect_target'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'unsafe_redirect_target', status, details, options)
    this.name = 'UnsafeRedirectTargetCredenceError'
  }
}

export class InvalidStellarAddressCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_stellar_address' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_stellar_address'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_stellar_address', status, details, options)
    this.name = 'InvalidStellarAddressCredenceError'
  }
}

export class BatchSizeTooSmallCredenceError extends CredenceError {
  static readonly errorCode = 'batch_size_too_small' as const

  constructor(
    message: string = DEFAULT_MESSAGES['batch_size_too_small'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'batch_size_too_small', status, details, options)
    this.name = 'BatchSizeTooSmallCredenceError'
  }
}

export class BatchSizeExceededCredenceError extends CredenceError {
  static readonly errorCode = 'batch_size_exceeded' as const

  constructor(
    message: string = DEFAULT_MESSAGES['batch_size_exceeded'],
    status: number = 413,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'batch_size_exceeded', status, details, options)
    this.name = 'BatchSizeExceededCredenceError'
  }
}

export class RequestTooLargeCredenceError extends CredenceError {
  static readonly errorCode = 'request_too_large' as const

  constructor(
    message: string = DEFAULT_MESSAGES['request_too_large'],
    status: number = 413,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'request_too_large', status, details, options)
    this.name = 'RequestTooLargeCredenceError'
  }
}

export class UnauthorizedCredenceError extends CredenceError {
  static readonly errorCode = 'unauthorized' as const

  constructor(
    message: string = DEFAULT_MESSAGES['unauthorized'],
    status: number = 401,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'unauthorized', status, details, options)
    this.name = 'UnauthorizedCredenceError'
  }
}

export class ForbiddenCredenceError extends CredenceError {
  static readonly errorCode = 'forbidden' as const

  constructor(
    message: string = DEFAULT_MESSAGES['forbidden'],
    status: number = 403,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'forbidden', status, details, options)
    this.name = 'ForbiddenCredenceError'
  }
}

export class CrawlerBlockedCredenceError extends CredenceError {
  static readonly errorCode = 'crawler_blocked' as const

  constructor(
    message: string = DEFAULT_MESSAGES['crawler_blocked'],
    status: number = 403,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'crawler_blocked', status, details, options)
    this.name = 'CrawlerBlockedCredenceError'
  }
}

export class NotFoundCredenceError extends CredenceError {
  static readonly errorCode = 'not_found' as const

  constructor(
    message: string = DEFAULT_MESSAGES['not_found'],
    status: number = 404,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'not_found', status, details, options)
    this.name = 'NotFoundCredenceError'
  }
}

export class ConflictCredenceError extends CredenceError {
  static readonly errorCode = 'conflict' as const

  constructor(
    message: string = DEFAULT_MESSAGES['conflict'],
    status: number = 409,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'conflict', status, details, options)
    this.name = 'ConflictCredenceError'
  }
}

export class OptimisticLockConflictCredenceError extends CredenceError {
  static readonly errorCode = 'optimistic_lock_conflict' as const

  constructor(
    message: string = DEFAULT_MESSAGES['optimistic_lock_conflict'],
    status: number = 409,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'optimistic_lock_conflict', status, details, options)
    this.name = 'OptimisticLockConflictCredenceError'
  }
}

export class IdempotencyKeyMismatchCredenceError extends CredenceError {
  static readonly errorCode = 'idempotency_key_mismatch' as const

  constructor(
    message: string = DEFAULT_MESSAGES['idempotency_key_mismatch'],
    status: number = 409,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'idempotency_key_mismatch', status, details, options)
    this.name = 'IdempotencyKeyMismatchCredenceError'
  }
}

export class InsufficientCreditsCredenceError extends CredenceError {
  static readonly errorCode = 'insufficient_credits' as const

  constructor(
    message: string = DEFAULT_MESSAGES['insufficient_credits'],
    status: number = 402,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'insufficient_credits', status, details, options)
    this.name = 'InsufficientCreditsCredenceError'
  }
}

export class SsrfBlockedCredenceError extends CredenceError {
  static readonly errorCode = 'ssrf_blocked' as const

  constructor(
    message: string = DEFAULT_MESSAGES['ssrf_blocked'],
    status: number = 422,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'ssrf_blocked', status, details, options)
    this.name = 'SsrfBlockedCredenceError'
  }
}

export class InsufficientFundsCredenceError extends CredenceError {
  static readonly errorCode = 'insufficient_funds' as const

  constructor(
    message: string = DEFAULT_MESSAGES['insufficient_funds'],
    status: number = 422,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'insufficient_funds', status, details, options)
    this.name = 'InsufficientFundsCredenceError'
  }
}

export class InvalidDisputeTransitionCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_dispute_transition' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_dispute_transition'],
    status: number = 422,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_dispute_transition', status, details, options)
    this.name = 'InvalidDisputeTransitionCredenceError'
  }
}

export class RateLimitExceededCredenceError extends CredenceError {
  static readonly errorCode = 'rate_limit_exceeded' as const

  constructor(
    message: string = DEFAULT_MESSAGES['rate_limit_exceeded'],
    status: number = 429,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'rate_limit_exceeded', status, details, options)
    this.name = 'RateLimitExceededCredenceError'
  }
}

export class InternalServerErrorCredenceError extends CredenceError {
  static readonly errorCode = 'internal_server_error' as const

  constructor(
    message: string = DEFAULT_MESSAGES['internal_server_error'],
    status: number = 500,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'internal_server_error', status, details, options)
    this.name = 'InternalServerErrorCredenceError'
  }
}

export class ServiceUnavailableCredenceError extends CredenceError {
  static readonly errorCode = 'service_unavailable' as const

  constructor(
    message: string = DEFAULT_MESSAGES['service_unavailable'],
    status: number = 503,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'service_unavailable', status, details, options)
    this.name = 'ServiceUnavailableCredenceError'
  }
}

export class MissingSecurityHeaderCredenceError extends CredenceError {
  static readonly errorCode = 'missing_security_header' as const

  constructor(
    message: string = DEFAULT_MESSAGES['missing_security_header'],
    status: number = 500,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'missing_security_header', status, details, options)
    this.name = 'MissingSecurityHeaderCredenceError'
  }
}

/**
 * @deprecated Legacy error code. Use `validation_failed` instead.
 */
export class InvalidInputCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_input' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_input'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_input', status, details, options)
    this.name = 'InvalidInputCredenceError'
  }
}

export class SdkRequestTimeoutCredenceError extends CredenceError {
  static readonly errorCode = 'sdk_request_timeout' as const

  constructor(
    message: string = DEFAULT_MESSAGES['sdk_request_timeout'],
    status: number = 0,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'sdk_request_timeout', status, details, options)
    this.name = 'SdkRequestTimeoutCredenceError'
  }
}

export class SdkNetworkErrorCredenceError extends CredenceError {
  static readonly errorCode = 'sdk_network_error' as const

  constructor(
    message: string = DEFAULT_MESSAGES['sdk_network_error'],
    status: number = 0,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'sdk_network_error', status, details, options)
    this.name = 'SdkNetworkErrorCredenceError'
  }
}

export class SdkInvalidJsonCredenceError extends CredenceError {
  static readonly errorCode = 'sdk_invalid_json' as const

  constructor(
    message: string = DEFAULT_MESSAGES['sdk_invalid_json'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'sdk_invalid_json', status, details, options)
    this.name = 'SdkInvalidJsonCredenceError'
  }
}

export class SdkUnmappedHttpCredenceError extends CredenceError {
  static readonly errorCode = 'sdk_unmapped_http' as const

  constructor(
    message: string = DEFAULT_MESSAGES['sdk_unmapped_http'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'sdk_unmapped_http', status, details, options)
    this.name = 'SdkUnmappedHttpCredenceError'
  }
}

export const CREDENCE_ERROR_REGISTRY = {
  'validation_failed': ValidationFailedCredenceError,
  'field_required': FieldRequiredCredenceError,
  'invalid_format': InvalidFormatCredenceError,
  'invalid_address': InvalidAddressCredenceError,
  'value_too_small': ValueTooSmallCredenceError,
  'value_too_large': ValueTooLargeCredenceError,
  'unexpected_field': UnexpectedFieldCredenceError,
  'invalid_type': InvalidTypeCredenceError,
  'unsafe_redirect_target': UnsafeRedirectTargetCredenceError,
  'invalid_stellar_address': InvalidStellarAddressCredenceError,
  'batch_size_too_small': BatchSizeTooSmallCredenceError,
  'batch_size_exceeded': BatchSizeExceededCredenceError,
  'request_too_large': RequestTooLargeCredenceError,
  'unauthorized': UnauthorizedCredenceError,
  'forbidden': ForbiddenCredenceError,
  'crawler_blocked': CrawlerBlockedCredenceError,
  'not_found': NotFoundCredenceError,
  'conflict': ConflictCredenceError,
  'optimistic_lock_conflict': OptimisticLockConflictCredenceError,
  'idempotency_key_mismatch': IdempotencyKeyMismatchCredenceError,
  'insufficient_credits': InsufficientCreditsCredenceError,
  'ssrf_blocked': SsrfBlockedCredenceError,
  'insufficient_funds': InsufficientFundsCredenceError,
  'invalid_dispute_transition': InvalidDisputeTransitionCredenceError,
  'rate_limit_exceeded': RateLimitExceededCredenceError,
  'internal_server_error': InternalServerErrorCredenceError,
  'service_unavailable': ServiceUnavailableCredenceError,
  'missing_security_header': MissingSecurityHeaderCredenceError,
  'invalid_input': InvalidInputCredenceError,
  'sdk_request_timeout': SdkRequestTimeoutCredenceError,
  'sdk_network_error': SdkNetworkErrorCredenceError,
  'sdk_invalid_json': SdkInvalidJsonCredenceError,
  'sdk_unmapped_http': SdkUnmappedHttpCredenceError,
} as const satisfies Record<string, CredenceErrorConstructor>

export type CredenceErrorCode = keyof typeof CREDENCE_ERROR_REGISTRY

export const CREDENCE_ERROR_CODES = Object.keys(CREDENCE_ERROR_REGISTRY) as CredenceErrorCode[]

export function isCredenceError(value: unknown): value is CredenceError {
  return value instanceof CredenceError
}

export function parseCredenceErrorEnvelope(body: string): CredenceErrorEnvelope | null {
  try {
    const parsed: unknown = JSON.parse(body)
    if (
      parsed != null &&
      typeof parsed === 'object' &&
      typeof (parsed as Record<string, unknown>).error === 'string' &&
      typeof (parsed as Record<string, unknown>).code === 'string'
    ) {
      const envelope = parsed as CredenceErrorEnvelope
      return {
        error: envelope.error,
        code: envelope.code,
        ...(envelope.details !== undefined ? { details: envelope.details } : {}),
      }
    }
  } catch {
    return null
  }
  return null
}

export function createCredenceErrorFromEnvelope(
  envelope: CredenceErrorEnvelope,
  status: number,
  options?: CredenceErrorOptions,
): CredenceError {
  const Ctor = CREDENCE_ERROR_REGISTRY[envelope.code as CredenceErrorCode]
  if (Ctor) {
    return new Ctor(envelope.error, status, envelope.details, options)
  }

  return new SdkUnmappedHttpCredenceError(
    envelope.error,
    status,
    envelope.details,
    options,
  )
}

export function createTransportCredenceError(
  code: Extract<
    CredenceErrorCode,
    'sdk_request_timeout' | 'sdk_network_error' | 'sdk_invalid_json' | 'sdk_unmapped_http'
  >,
  message: string,
  status: number,
  options?: CredenceErrorOptions,
): CredenceError {
  const Ctor = CREDENCE_ERROR_REGISTRY[code]
  return new Ctor(message, status, undefined, options)
}
