[package]
name = "credence-bond"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"
description = "Credence bond smart contract — Soroban/Stellar"
license = "MIT"
repository = "https://github.com/CredenceOrg/Credence-Contracts"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[dependencies]
soroban-sdk = "20.0.0"

[dev-dependencies]
soroban-sdk = { version = "20.0.0", features = ["testutils"] }
