import fs from 'fs'
import path from 'path'
import { fileURLToPath, pathToFileURL } from 'url'
import {
  ERROR_CATALOG,
  ERROR_CODE_DEPRECATIONS,
  ERROR_LOCALIZATION_CATALOG,
  type ErrorCatalogEntry,
  type ErrorCodeDeprecation,
} from '../src/lib/errorCatalog.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
export const DEFAULT_OUTPUT_PATH = path.resolve(__dirname, '../docs/error-codes.md')

export const escapeMarkdown = (value: string): string => value.replace(/\|/g, '\\|')

export const formatEntryRow = (entry: ErrorCatalogEntry): string => [
  `\`${entry.code}\``,
  String(entry.httpStatus),
  entry.category ?? '',
  escapeMarkdown(entry.defaultMessage),
].join(' | ')

/**
 * Active (kind === 'api') entries, deterministically sorted by
 * category -> httpStatus -> code so re-generating the doc from an
 * unordered catalog object never produces a diff-only-by-order churn.
 * Missing category/httpStatus (boundary inputs from a malformed catalog
 * entry) sort as '' / 0 respectively rather than throwing.
 */
export const buildActiveEntries = (
  catalog: Record<string, ErrorCatalogEntry>
): ErrorCatalogEntry[] =>
  Object.values(catalog)
    .filter((entry) => entry.kind === 'api')
    .sort((a, b) => {
      const catA = a.category ?? ''
      const catB = b.category ?? ''
      if (catA !== catB) return catA.localeCompare(catB)
      const statusA = a.httpStatus ?? 0
      const statusB = b.httpStatus ?? 0
      if (statusA !== statusB) return statusA - statusB
      return a.code.localeCompare(b.code)
    })

/** Deprecated entries, sorted by code for deterministic output. */
export const buildDeprecatedEntries = (
  deprecations: Record<string, ErrorCodeDeprecation>
): ErrorCodeDeprecation[] => Object.values(deprecations).sort((a, b) => a.code.localeCompare(b.code))

/** One markdown table row per locale in the localization catalog. */
export const buildLocalizationRows = (
  localizationCatalog: Record<string, Record<string, string>>
): string[] =>
  Object.entries(localizationCatalog).map(([locale, messages]) => {
    const count = Object.keys(messages).length
    return `| \`${locale}\` | ${count} messages | Catalog default messages for active codes. |`
  })

export const buildDeprecatedSection = (deprecatedEntries: ErrorCodeDeprecation[]): string[] => {
  if (deprecatedEntries.length === 0) {
    return ['No error codes are currently deprecated.', '']
  }
  return [
    '| Code | Deprecated since | Replacement | Reason |',
    '| --- | --- | --- | --- |',
    ...deprecatedEntries.map((entry) => {
      const replacement = entry.replacement ? `\`${entry.replacement}\`` : 'None'
      return `| \`${entry.code}\` | ${entry.deprecatedSince} | ${replacement} | ${escapeMarkdown(entry.reason)} |`
    }),
    '',
  ]
}

export interface ErrorDocsInput {
  catalog: Record<string, ErrorCatalogEntry>
  deprecations: Record<string, ErrorCodeDeprecation>
  localizationCatalog: Record<string, Record<string, string>>
}

/** Pure: builds the full markdown document. No I/O, deterministic for a given input. */
export const buildErrorDocsContent = ({
  catalog,
  deprecations,
  localizationCatalog,
}: ErrorDocsInput): string => {
  const activeEntries = buildActiveEntries(catalog)
  const deprecatedEntries = buildDeprecatedEntries(deprecations)
  const localizationRows = buildLocalizationRows(localizationCatalog)

  const lines: string[] = [
    '<!-- This file is generated by scripts/generate-error-docs.ts. Do not edit manually. -->',
    '',
    '# Credence API Error Codes',
    '',
    'This reference is generated from `src/lib/errorCatalog.ts` and is the source of truth for machine-readable API error codes.',
    '',
    '## Stability contract',
    '',
    '- Error-code strings are stable public API values. Consumers may safely branch on `code` (and the `error_code` alias where present).',
    '- New codes may be added in minor releases.',
    '- Existing codes must not be removed or renamed without adding a deprecation entry in `ERROR_CODE_DEPRECATIONS`.',
    '- HTTP statuses, categories, and default messages are catalog-managed so handlers do not invent uncatalogued responses.',
    '- Production responses use catalog default messages and omit details to avoid leaking PII, stack traces, or chained error internals.',
    '',
    '## Active codes',
    '',
    '| Code | HTTP status | Category | Default message |',
    '| --- | ---: | --- | --- |',
    ...activeEntries.map((entry) => `| ${formatEntryRow(entry)} |`),
    '',
    '## Localization catalog',
    '',
    '`ERROR_LOCALIZATION_CATALOG` currently ships default English (`en`) messages keyed by error code. Add locales in the catalog before returning localized production responses.',
    '',
    '| Locale | Coverage | Notes |',
    '| --- | ---: | --- |',
    ...localizationRows,
    '',
    '## Deprecated codes',
    '',
    ...buildDeprecatedSection(deprecatedEntries),
  ]

  return `${lines.join('\n')}\n`
}

/**
 * Writes the generated content to disk, creating the parent directory if
 * needed. Left as a thin, separately-testable wrapper around fs so
 * permission/IO failures (EACCES, ENOSPC, a read-only mount, …) can be
 * exercised without touching the real filesystem, and so a failure here
 * surfaces as a thrown error rather than a partially-written or silently
 * dropped file.
 */
export const writeErrorDocs = (outputPath: string, content: string): void => {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, content, 'utf-8')
}

export interface RunGenerateErrorDocsOptions {
  outputPath?: string
  catalog?: Record<string, ErrorCatalogEntry>
  deprecations?: Record<string, ErrorCodeDeprecation>
  localizationCatalog?: Record<string, Record<string, string>>
  log?: (message: string) => void
}

/**
 * Orchestrates the full generate-and-write flow. Defaults to the real
 * catalog and the real output path so `tsx scripts/generate-error-docs.ts`
 * behaves exactly as before; every input is overridable for tests so
 * boundary/malformed-catalog and write-failure paths can be exercised
 * without mutating global state or the real docs file.
 */
export const runGenerateErrorDocs = (options: RunGenerateErrorDocsOptions = {}): string => {
  const outputPath = options.outputPath ?? DEFAULT_OUTPUT_PATH
  const catalog = options.catalog ?? ERROR_CATALOG
  const deprecations = options.deprecations ?? ERROR_CODE_DEPRECATIONS
  const localizationCatalog = options.localizationCatalog ?? ERROR_LOCALIZATION_CATALOG
  const log = options.log ?? console.log

  const content = buildErrorDocsContent({ catalog, deprecations, localizationCatalog })
  writeErrorDocs(outputPath, content)
  log(`Error-code reference generated at ${path.relative(path.resolve(__dirname, '..'), outputPath)}`)
  return outputPath
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  runGenerateErrorDocs()
}
